export const SHOW_PRODUCT = 'SHOW_PRODUCT';
export const ADD_TO_CART = 'ADD_TO_CART';
export const CHANGE_MESSAGE = 'CHANGE_MESSAGE';
export const DELETE_PRODUCT_IN_CART = 'DELETE_PRODUCT_IN_CART';
export const UPDATE_QUANTITY = 'UPDATE_QUANTITY';